# Generated by Django 5.0.6 on 2024-06-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('desc', models.CharField(max_length=500)),
                ('details', models.CharField(max_length=500)),
                ('cat', models.CharField(default='Category', max_length=50)),
                ('image1', models.ImageField(upload_to='technest/images/products')),
                ('image2', models.ImageField(upload_to='technest/images/products')),
                ('image3', models.ImageField(upload_to='technest/images/products')),
                ('image4', models.ImageField(upload_to='technest/images/products')),
            ],
        ),
    ]
